database = "postgres://danielle@localhost:5432/otter?sslmode=disable"

[[stores]]
queries = "./internal/engine/pgengine/database/queries"

package.name = "database"
package.path = "./internal/engine/pgengine/database"
