// Code generated by otter (v0.0.0-dev+1d31a5d). DO NOT EDIT.
package database

import (
	"context"
	"github.com/jackc/pgx/v5"
)

type Store interface {
	GetColumnNullability(ctx context.Context, params GetColumnNullabilityParams) (bool, error)
	GetEnumVariantsByOID(ctx context.Context, oid uint32) ([]string, error)
	GetRelationNullability(ctx context.Context, params GetRelationNullabilityParams) ([]bool, error)
	GetTypeByOID(ctx context.Context, oid uint32) (GetTypeByOIDRow, error)
}

type Querier struct {
	db *pgx.Conn
}

func New(db *pgx.Conn) *Querier {
	return &Querier{db: db}
}
