// Code generated by otter (v0.0.0-dev+1d31a5d). DO NOT EDIT.
package database

import "context"

type GetColumnNullabilityParams struct {
	Schema     string
	Relation   string
	ColumnName string
}

func (q *Querier) GetColumnNullability(ctx context.Context, params GetColumnNullabilityParams) (bool, error) {
	var item bool
	if err := q.db.QueryRow(ctx, "-- :one\n-- $1: schema\n-- $2: relation\n-- $3: column_name\nselect is_nullable = 'YES' from information_schema.columns where table_schema = $1 and table_name = $2 and column_name = $3 limit 1", params.Schema, params.Relation, params.ColumnName).Scan(&item); err != nil {
		return item, err
	}
	return item, nil
}

func (q *Querier) GetEnumVariantsByOID(ctx context.Context, oid uint32) ([]string, error) {
	rows, err := q.db.Query(ctx, "-- :many\n-- $1: oid\nselect enumlabel from pg_enum where enumtypid = $1 order by enumsortorder", oid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []string
	for rows.Next() {
		var item string
		if err := rows.Scan(&item); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

type GetRelationNullabilityParams struct {
	Schema   string
	Relation string
}

func (q *Querier) GetRelationNullability(ctx context.Context, params GetRelationNullabilityParams) ([]bool, error) {
	rows, err := q.db.Query(ctx, "-- :many\n-- $1: schema\n-- $2: relation\nselect is_nullable = 'YES' from information_schema.columns where table_schema = $1 and table_name = $2 order by ordinal_position", params.Schema, params.Relation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []bool
	for rows.Next() {
		var item bool
		if err := rows.Scan(&item); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

type GetTypeByOIDRow struct {
	Name    string
	Type    byte
	NotNull bool
}

func (q *Querier) GetTypeByOID(ctx context.Context, oid uint32) (GetTypeByOIDRow, error) {
	var item GetTypeByOIDRow
	if err := q.db.QueryRow(ctx, "-- :one\n-- $1: oid\nselect\n    typname as \"name\",\n    typtype as \"type\",\n    typnotnull as \"not_null\"\nfrom pg_type where oid = $1 limit 1", oid).Scan(&item.Name, &item.Type, &item.NotNull); err != nil {
		return item, err
	}
	return item, nil
}
